### ISSUE TITLE
Does python-fire have some method to do unified exception handling?

### ISSUE THREAD

**Issue by hujianxin** [google/python-fire#142] opened 2018-09-29 01:53 UTC

**Comment by kinow** [comment] 2019-03-12 21:33
Came here looking for the same (as I knew [click had it](http://click.palletsprojects.com/en/5.x/exceptions/)). Couldn't find anything in docs/examples, so I guess it leaves that part to the user?

**Comment by dbieber** [comment] 2019-07-26 17:58
That's correct.

If there's an error caused by the user's usage (e.g. they try to access a command that doesn't exist, or don't provide required arguments for a command), then internally Fire raises a `FireError` with details about that error. Fire catches its own errors though, and will raise a `FireExit` (a subclass of `SystemExit` that contains information about the error) with status code 2, indicating a user error.

If there's a Python error in the CLI, then Fire doesn't catch it; it simply surfaces to the user as a Python error. You can certainly catch errors raised by CLI (both ordinary Python errors as well as `FireExit`s) if you want custom error handling code.

**Comment by dbieber** [comment] 2019-08-16 19:03
Here's the real answer to your question:

Yes, Fire catches `fire.core.FireErrors` and displays them succinctly alongside the usage information for the component at the time of the error.

So e.g. you can do something like

```
import fire, math
def sqrt(x):
  if x < 0:
    raise fire.core.FireError('x must be >= 0')
  return math.sqrt(x)
fire.Fire(sqrt)
```

Then when you use it you'll see:
```
> cli -2
ERROR: x must be >= 0
Usage: mathex.py X

For detailed information on this command, run:
  mathex.py --help
```

Sorry it's not in the docs yet!

**Comment by dbieber** [comment] 2020-03-10 16:51
Answered in previous comment; closing!

**Closed by dbieber** 2020-03-10 16:51 UTC
Labels: question
