### ISSUE TITLE
annotation @functools.lru_cache() on functions with parameters breaks python-fire

### ISSUE THREAD

**Issue by borislopezaraoz** [google/python-fire#145] opened 2018-10-26 23:15 UTC
Steps to reproduce:

```
import functools

@functools.lru_cache()
def hello(name):
    return 'hello ' + name
```

```
python hello.py hello name
...
TypeError: hello() missing 1 required positional argument: 'name'

```

**Comment by dbieber** [comment] 2018-10-29 16:28
Thanks for raising this to our attention.
This works in Python 2:

```
import fire
import functools32

@functools32.lru_cache()
def hello(name):
    return 'hello ' + name

fire.Fire()
```

but as you say, it fails in Python 3. Marking as a bug. Will keep you posted on progress.

**Comment by robertvazan** [comment] 2019-04-07 15:19
This is probably caused by #159.

**Comment by dbieber** [comment] 2019-07-30 19:24
Yeah, I can confirm that implementing #159 will resolve this.

**Comment by dbieber** [comment] 2020-02-28 23:23
Resolved by #203 (though still broken in Python 3.4)

**Closed by dbieber** 2020-02-28 23:23 UTC
Labels: bug, help wanted
