### ISSUE TITLE
Erroneous printing of OrderedDicts in Python 3.5

### ISSUE THREAD

**Issue by michaelbilow** [google/python-fire#163] opened 2019-02-07 15:12 UTC
Discovered this strange bug yesterday, where `OrderedDict` prints out of order on Python 3.5 (but not 3.6).

```bash
$ cat <<'EOF' > test_fire.py
import fire
from collections import OrderedDict

def test():
    data = [('a', 1), ('b', 2), ('c', 3)]
    return OrderedDict(data)

if __name__ == "__main__":
    fire.Fire(test)

EOF
$ conda create -n test35 python=3.5
$ source activate test35
(test35) $ pip install fire
(test35) $ conda list | grep fire
fire                      0.1.3                    pypi_0    pypi
(test35) $ python test_fire.py
a: 1
b: 2
c: 3
(test35) $ python test_fire.py
a: 1
c: 3
b: 2
(test35) $ python test_fire.py
c: 3
a: 1
b: 2
(test35) $ conda deactivate
$ conda create -n test36 python=3.6
$ source activate 
(test36) $ pip install fire
(test36) $ conda list | grep fire
fire                      0.1.3                    pypi_0    pypi
(test36) $ python test_fire.py
a: 1
b: 2
c: 3
(test36) $ python test_fire.py
a: 1
b: 2
c: 3
(test36) $ python test_fire.py
a: 1
b: 2
c: 3
(test36) $ python test_fire.py
a: 1
b: 2
c: 3
(test36) $ python test_fire.py
a: 1
b: 2
c: 3
```

**Comment by dbieber** [comment] 2019-02-08 15:53
You can see where this happens in the source at [core.py#L243](https://github.com/google/python-fire/blob/master/fire/core.py#L243). At line 284 we iterate through the items in order `for key, value in result.items():` so that's where the intended behavior is supposed to come from.

**Comment by Nikhilkoneru** [comment] 2019-07-06 02:01
I will work on this issue

**Comment by vbarbaresi** [comment] 2019-10-07 12:56
I can't reproduce this issue with Python 3.5.4 on OSX. I looped the test thousands of times and the output is always in the right order.

I checkouted the code at the time this issue was written, to make sure it wasn't fixed since.

OrderedDicts have been reimplemented in 3.5, maybe there were issues in the early versions?

**Comment by dbieber** [comment] 2019-10-09 18:36
Thanks for trying to reproduce. I have not reproduced this either.
@Nikhilkoneru did you make any progress when you went to work on this back in July?

**Comment by dbieber** [comment] 2020-03-06 22:18
Going to close this since @vbarbaresi and I weren't able to reproduce. If you run into this issue again though, definitely feel free to reopen or open a new issue!

**Closed by dbieber** 2020-03-06 22:18 UTC
Labels: bug, help wanted
